# Generated by Django 5.1.2 on 2024-10-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('AccNo', models.IntegerField(primary_key='AccNo', serialize=False)),
                ('LoanAmt', models.IntegerField()),
                ('Interest', models.IntegerField()),
            ],
        ),
    ]
