# Generated by Django 5.1.2 on 2024-10-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detroit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='PhoneNo',
            field=models.IntegerField(default=1234567890, max_length=10),
        ),
    ]
